### ISSUE TITLE
EPIC: Mobile Wallet functionality

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/js#150]
```[tasklist]
### Tasks
- [x] Add ThirdWebProvider
- [x] Replace current ConnectButton component with Thirdweb ConnectWallet component
- [x] Release dev track
- [x] Deploy Dashboard to Staging
- [ ] Release SDK
- [ ] Deploy Dashboard to Production
```

## Acceptance Criteria
- [ ] A user a can connect their wallet using the Thirdweb Wallet via the OPENFORMAT SDK
