### ISSUE TITLE
Transaction Fees

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/js#152]
## Problem
We are current rewarding users $OFT for completing missions. We now need to implement transaction fees so users can spend them.

## Solution
There is couple of ways of doing this:

1. Requesting a small amount of $OFT at a contact level. This means if the developer runs out of $OFT, the contracts will fail. This could cause issues with automated contract interactions.
2. Tracking the number of contract calls and then requesting the amount of $OFT at the end of each month. 
3. We could request the $OFT at an SDK level. Developers that call the contract directly, would be able to bypass the transaction fees.
4. We could track the number of SDK/API calls and bill accordingly.

First step is for team to get together and talk through options.

## Acceptance Criteria
- A developer is charged an amount (TBC) of $OFT each time they interact with the OPENFORMAT SDK.
```[tasklist]
### Tasks
- [x] Before all SDK calls, request 1 $OFT from caller
- [x] Write unit tests
- [x] Release to dev tracks
- [x] Deploy to Staging
- [ ] SDK Release
- [ ] Update @openformat/react to latest version in Dashboard
```
